version: "3.7"
services:
    postgres:
        image: postgres:latest
        ports:
            - ${DB_PORT}:${DB_PORT}
        env_file:
            - ./.env
        networks:
            net_ecommerce_user:
                ipv4_address: 172.16.101.2
    pgAdmin4:
        image: dpage/pgadmin4
        env_file:
            - ./.env
        depends_on:
            - postgres
        ports:
            - 8080:80
        networks:
            net_ecommerce_user:
                ipv4_address: 172.16.101.3

    ecommerce_user:
        build:
            context: .
            dockerfile: docker/Dockerfile.ecommerce_user
        container_name: elixir
        depends_on:
            - postgres
            - pgAdmin4
        env_file:
            - ./.env
        ports:
            - ${GRPC_PORT}:${GRPC_PORT}
        volumes:
            - "./:/opt/app"
        networks:
            net_ecommerce_user:
                ipv4_address: 172.16.101.4
networks:
    net_ecommerce_user:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.101.0/24