apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: ecommerce-user-db
  labels:
    db: ecommerce-user-db
spec:
  ports:
    - name: db
      port: 5432
      targetPort: 5432